name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Elm
      uses: justgook/setup-elm@v1

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.x

    - name: Set yarn
      id: yarn
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
        echo "::add-path::$(yarn bin)"
        echo "::add-path::$(yarn global bin)"

    - name: Get Yarn cache
      uses: actions/cache@v1.0.3
      id: yarn-cache-exists
      with:
        path: ${{ steps.yarn.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install elm-test
      run: yarn global add elm-test@0.19.1-revision2

    - name: Test
      env:
        ELM_HOME: ${{ steps.elm-home.outputs.dir }}
      run: elm-test

    - name: Install Dependencies
      #if: steps.yarn-cache-exists.outputs.cache-hit != 'true'
      run: |
        yarn
        echo "::add-path::$(yarn bin)"
      working-directory: examples

    - name: Build
      run: elm make src/Shmup.elm --optimize --output=./gh-pages/bundle.js
      working-directory: examples

#    - uses: ./.github/actions/hello-world-action
    - name: Optimize Javascript
      env:
        NODE_ENV: production
      working-directory: examples
      run: |
        jscodeshift -t transform.js ./gh-pages/bundle.js
        uglifyjs ./gh-pages/bundle.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters" --output=./gh-pages/bundle.js --reserved-names "__optimize"
        prepack ./gh-pages/bundle.js --inlineExpressions --out ./gh-pages/bundle.js --maxStackDepth  10000  --invariantLevel 3
        uglifyjs ./gh-pages/bundle.js --compress 'keep_fargs=false,unsafe_comps,unsafe' --mangle --output=./gh-pages/bundle.js
        posthtml ./gh-pages/index.html -o ./gh-pages/index.html -c posthtml.config.js

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.0.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: examples/gh-pages
